services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata_new:/var/lib/postgresql/data
    networks:
      - film-network

  backend:
    build: ./backend
    image: ghcr.io/alinakharagezian/film-backend:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LOGGER_TYPE=tskv
    depends_on:
      - postgres
    networks:
      - film-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=/api/afisha
        - VITE_CDN_URL=/content/afisha
    image: ghcr.io/alinakharagezian/film-frontend:latest
    restart: unless-stopped
    volumes:
      - frontend_dist:/app/dist
    networks:
      - film-network

  nginx:
    build: ./nginx
    image: ghcr.io/alinakharagezian/film-nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - frontend_dist:/usr/share/nginx/html
    networks:
      - film-network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - film-network

networks:
  film-network:
    driver: bridge

volumes:
  pgdata_new:
  pgadmin_data:
  frontend_dist: